name: Electron

on: pull_request

jobs:
  build-react:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: yarn install
        run: |
          yarn install
          
      - name: Build react
        run: |
          yarn run build:react
          
      - name: Upload react artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-artifact
          path: |
            build
  build-forge:
    needs: build-react
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: yarn install
        run: |
          yarn install
          
      - name: Build react
        run: |
          yarn run build:react
          
      - name: Upload react artifact
        uses: actions/upload-artifact@v2
        with:
          name: react-artifact
          path: |
            build
            
      - name: Download react artifact
        uses: actions/download-artifact@v2
        with:
          name: react-artifact
          
      - name: Build electron
        run: |
          yarn run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact-${{ matrix.os }}
          path: |
            out
