name: Electron

on: push

jobs:
  install: 
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: yarn install
        run: |
          yarn install
  build-react:
    needs: install
    runs-on: ubuntu-latest
    
    steps:
      - name: Build react
        run: |
          yarn run build:react
  build-forge:
    needs: build-react
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Build electron
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn run build
