name: Electron
on:
  push:
    branches:
      - master
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: electron
    - uses: actions/setup-node@master
      with:
        node-version: 10.16
    - name: See directory
      run: ls
  build_on_win:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@master
        with:
          ref: feature/github-actions        
      - uses: actions/setup-node@master
        with:
          node-version: 10.16
      - name: See directory
        run: ls
